# https://travis-ci.org/
branches:
  only:
    - master
    - jdk-8

language: java
jdk:
  - oraclejdk8
  - oraclejdk9

before_install:
  - mvn license:format --quiet -B

after_success:
  - mvn clean test jacoco:report coveralls:report
