# https://travis-ci.org/
branches:
  only:
    - master

language: java
jdk:
  - oraclejdk11
  - openjdk11

before_install:
  - mvn license:format --quiet -B

after_success:
  - mvn clean test jacoco:report coveralls:report
